name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AnantSaxena11
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, shell
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: commit
          filename: metrics.svg
          committer_branch: main
          committer_message: "chore: update metrics [skip ci]"

      - name: Generate half-year isometric calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AnantSaxena11
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Kolkata
          output_action: commit
          filename: metrics-isocalendar.svg
          committer_branch: main
          committer_message: "chore: update isocalendar metrics [skip ci]"
